apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: wager-tests
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Scoped project for ephemeral wager test environments

  sourceRepos:
    - https://github.com/sg-is-devops/helm

  destinations:
    - server: 
      namespace: wager-test-*

  clusterResourceWhitelist:
    - group: ''
      kind: Namespace

  namespaceResourceWhitelist:
    # Core
    - group: ''
      kind: Secret
    - group: ''
      kind: ConfigMap
    - group: ''
      kind: Service
    - group: ''
      kind: ServiceAccount
    - group: ''
      kind: LimitRange
    - group: ''
      kind: ResourceQuota
    - group: ''
      kind: PersistentVolumeClaim
    # Apps
    - group: apps
      kind: Deployment
    - group: apps
      kind: StatefulSet
    - group: apps
      kind: ReplicaSet
    # Batch
    - group: batch
      kind: Job
    - group: batch
      kind: CronJob
    # RBAC
    - group: rbac.authorization.k8s.io
      kind: Role
    - group: rbac.authorization.k8s.io
      kind: RoleBinding
    # Networking
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: networking.k8s.io
      kind: Ingress

  roles:
    - name: ci-deployer
      description: GitHub Actions pipeline
      policies:
        - p, proj:wager-tests:ci-deployer, applications, *, wager-tests/*, allow
